title: Mark Aboagye # your name (or website title) here
logo: "/images/prof_pic.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This is my online platform to share my Data Science projects 
  <br> This is my online platform to share my Data Science projects <br>
  Second description 
  <br><br>
  <i class="fa fa-linkedin"></i> <a href="https://www.linkedin.com/in/marksefa/">View My LinkedIn Profile</a>
  <br><br>
  <a href="/files/Mark_Resume_Jun24.html">View My CV</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
