title: Mark Aboagye # your name (or website title) here
logo: "/https://media-exp1.licdn.com/dms/image/D4E03AQGKoItTpyvXsw/profile-displayphoto-shrink_800_800/0/1664625811640?e=1672876800&v=beta&t=gvQrnV4UKIgiU1K4eqUKT_RxHyFiUjdWboEhFwOXbIA?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br> This is my online platform to share my Data Science projects <br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/marksefa/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
